name: design_system
description: Flutter design system package that contains themed components, colors pallete and fonts.
version: 1.0.3
homepage: https://github.com/reemjadallah96/design_system

environment:
  sdk: '>=2.10.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

